### PR TITLE
Fix SIGSEGV in gtest death tests due to small stack

### PR DESCRIPTION
**Pull request by AngryLoki**
In https://github.com/google/googletest/blob/v1.14.0/googletest/src/gtest-death-test.cc#L1307 on x86-64 gtest allocates 8192 bytes for `clone`:

```c
static pid_t ExecDeathTestSpawnChild(char* const* argv, int close_fd) {
    const auto stack_size = static_cast<size_t>(getpagesize() * 2);
    ...
    child_pid = clone(&ExecDeathTestChildMain, stack_top, SIGCHLD, &args);
```

After that attempt to call execv is intercepted by libsandbox.so, which allocates `SB_PATH_MAX` (8192) + more bytes multiple times on stack, causing SIGSEGV (instead of expected types of crashes).

This PR moves all allocations for related function to heap, so now call path fits `getpagesize() * 2` with large margin.

Bug: https://bugs.gentoo.org/923013

### CODE REVIEW

**Comment by thesamesam** [comment]
@floppym

**Comment by floppym** [comment]
I was under the impression that we were avoiding malloc on purpose in libsandbox, but I don't know where I got that impression.

I suppose we can give it a try and see if anything breaks.

**Comment by floppym** [comment]
Ah, I see we already use malloc in libsandbox, so disregard the above.

**Review by floppym — APPROVED** [review]

**Comment by cheneytianx** [comment]
Thanks, I was facing the same issue.

**Pull request closed without merging**
